name: Build
on:
  workflow_dispatch: {}
  push:
    branches-ignore:
    - develop
    paths-ignore:
    - '**/.md'
  pull_request:
    paths-ignore:
    - '**/.md'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Setup Java
      uses: actions/setup-java@v4.7.1
      with:
        distribution: adopt
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.4.2
    - name: Build
      run: ./gradlew check --info
      shell: bash
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5.6.2
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_annotations: 'true'
        update_check: 'true'
    - name: Release (if required)
      id: get-version
      if: github.ref == 'refs/heads/main'
      run: |-
        # some script content goes here!
        echo "Version did not change on this commit. Ignoring"
        echo "tag-created=false" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}
      shell: bash
    - name: Trigger release workflow
      uses: peter-evans/repository-dispatch@v3
      if: github.ref == 'refs/heads/main' && steps.get-version.outputs.tag-created
        == 'true'
      with:
        token: ${{ secrets.WORKFLOWS_TOKEN }}
        event-type: release
        client-payload: '{"tag": "${{ steps.get-version.outputs.tag }}"}'
